<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>Test helpers for Entity Framework Core, such as checking a DbContext's entity mapping.</Description>
    <Nullable>enable</Nullable>
  </PropertyGroup> 

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
  </ItemGroup>

</Project>
